alias upgrade="sudo apt autoremove -y; sudo apt update && sudo apt upgrade -y"
alias wcl="wc -l"
alias less="less -Sn"
alias untar="tar xvzf"
alias dirs="dirs -p"
alias vi="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"
